### ISSUE TITLE
Open Service Broker Integration

### ISSUE THREAD

**Issue by hikhvar** [awslabs/aws-service-operator#110]
Hello, 
are there any plans to integrate into the [Open Service Broker API](https://www.openservicebrokerapi.org/)? The goals of this operator and that API seem to be similar.

**Comment by christopherhein** [comment]
Hey @hikhvar we actually already have an [AWS Service Broker](https://aws.amazon.com/partners/servicebroker/) which implements the OSB API, the goals of this project are similar but without the need for the Service Catalog API and being closer to a pure K8s implementation. 

Closing this issue.
