### ISSUE TITLE
Add support for creating CloudFormation stacks from template URLs or inline templates

### ISSUE THREAD

**Issue by devkid** [awslabs/aws-service-operator#116]
All resources created by the aws-service-operator are created via CloudFormation anyways. It would make sense to have a way of creating CloudFormation stacks using custom resources. This would also allow to create any resource that is supported by CloudFormation.

**Comment by christopherhein** [comment]
There is actually another project which does this exact thing. https://github.com/linki/cloudformation-operator/ The AWS Service Operators goals are a little different bringing AWS resources closer to the core of how Kubernetes defines objects. With the AWS Service Operator, we're adding in additional hooks which give it the ability to create k8s native components, Services, ConfigMaps, Secrets as well the other difference is configuring the operator to get more back from the stacks that are managed by using the outputs.
