### ISSUE TITLE
Allow Support for Creating Secrets

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#44]
Just like support for #43 but this one will create Kubernetes Secrets.

**Comment by icereed** [comment]
Hi @christopherhein, 
this sounds like a really useful feature since we want to use RDS databases and want to use the output of CFN in a secret.
Is there any possibility it will be added?

Thanks so much!

**Comment by icereed** [comment]
@christopherhein, Could you point me where I would need to adapt stuff in order to implement secrets creation?

**Comment by pierreozoux** [comment]
@icereed check this, it might be helpful: https://blog.byte.builders/post/the-case-for-appbinding/

**Comment by icereed** [comment]
Hi @pierreozoux, as I understand the AppBinding concept correctly, I still would need to create a secret, right?
