### ISSUE TITLE
Write Helm Chart with Args as Values

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#82]
This will make the setup even easier.

```
helm install incubator/aws-service-operator --set bucket=foobar region=us-west-2
```

**Comment by acaire** [comment]
I've just about finished writing this - Should I PR this directly to https://github.com/helm/charts or did you want a PR against this repo?

**Comment by christopherhein** [comment]
@acaire Thank you so much! Would you mind doing both and commenting referencing each other?

**Comment by christopherhein** [comment]
Or it might be best to start here and when I get the dev/release cluster automation setup we can have that create the releases against the `helm` repo… thoughts?
